Change the Web Server port 5000 to port 80
beyond-io/beyond pull request #168
Opened 2020-11-09 07:15 UTC by rliberma

Change the Web Server port 5000 to port 80 issue #167 

Changed has been done to the relevant files:
bootstrap-infra.py:            'FromPort': 80,
bootstrap-infra.py:            'ToPort': 80,
tests/test_sanity.py:    response = requests.get("http://localhost:80")
tests/functional/test_title.py:    selenium.get('http://localhost:80')
tests/http_get_test.sh:if [ $(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:80) = $exp_response ]; then
Vagrantfile:    dev.vm.network "forwarded_port", guest: 80, host: 80

2020-11-09 10:56 UTC, lioramilbaum commented
Issue?

2020-11-09 10:57 UTC, lioramilbaum requested changes
Have you tried spinning a dev environment with this PR? Does it work for you?
Please provide unit tests.

2020-11-09 12:52 UTC, rliberma commented
> Issue?

Linked.

2020-11-10 08:10 UTC, IlanZuckerman reviewed
LGTM

2020-11-10 08:40 UTC, lioramilbaum commented
@rliberma No need to list the changed files in the PR description. The information is already provided in the 'Files Changed' tab. 
I will try to spin a dev environment to check that it works for me before I approve the change.

2020-11-22 06:54 UTC, rliberma commented
As agreed in our last meeting we are keeping port 5000 at this phase. i am closing this PR.

2020-11-22 06:54 UTC, closed without merging